baseURL = 'https://enkidu.site/'
title = "Enkidu"
theme = "reimu"
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-cn' #与文件夹路径保持统一小写
defaultContentLanguageInSubdir = true

# SEO 核心
enableRobotsTXT = true
enableSitemap = true
noindex = false

# 站点地图配置，强制生成多语言子站sitemap
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# 全局参数
[params]
  keywords = ["恩奇都", "Enkidu", "FGO","FSF", "粉丝网站", "同人创作"]

[languages]
    [languages.zh-CN]
        languageName = '简体中文'
        hasCJKLanguage = true
        contentDir = 'content/zh-cn'
        weight = 1
        [languages.zh-CN.params]
            description = "恩奇都粉丝应援网站"
            subtitle = "恩奇都粉丝应援网站"
    [languages.en]
        languageName = "English" 
        hasCJKLanguage = false
        contentDir = 'content/en'
        weight = 2
        [languages.en.params]
            description = "Fan Support Website"
            subtitle = "Fan Support Website"


[outputs]
    home = ["Algolia","HTML","Sitemap"]

[outputFormats.Algolia]
    baseName = "algolia" 
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true